### ISSUE TITLE
Add PowerShell Support

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/azure-functions-devops-build#29]
add the ability to create a pipeline for a PowerShell function
@ahmedelnably will check the needed steps and circle back with requirements

Target Milestone: Azure CLI Milestone 59

**Comment by ahmedelnably** [comment]
@Hazhzeng  talked with @eamonoreilly, the only thing needed for PowerShell is:
Package the code
release the code

there are no other steps needed to Support PS.

Note that this is only supported for Windows for the time being

**Comment by Hazhzeng** [comment]
This issue is fixed in https://github.com/Azure/azure-cli/pull/9040
